openapi: 3.0.3
info:
  version: "1.3.2"
  title: TARMED Validator API
  description: |
    API for requesting & validating TARMED Data.
    
    By the `/validate` endpoint, it is possible to validate multiple TARMED positions on a invoice for validity. The endpoint `/validate-invoices` can validate multiple invoices (e.g. to full history of a patient) to verify, if the TARMED tarifs are valid to us (quantity, cumulation and much more).
    
    The `ErrorCode`(see below) schema gives a overview about the implemented validation possibilities.
    
    Please contact me (info@tarmed-validator.ch) for an API-Key.

    Status, roadmap, bugtracker and more information can be found at GitHub: [https://github.com/mitosch/tarmed-validator-api-doc](https://github.com/mitosch/tarmed-validator-api-doc)
    
    Descriptions of TARMED values refer to the original MS Access database (e.g. `Leistungsnummer (LEISTUNG.LNR)`).
    
    For more information about TARMED, please visit these resources:
    
      * [Tarifsystem TARMED, Bundesamt fÃ¼r Gesundheit](https://www.bag.admin.ch/bag/de/home/versicherungen/krankenversicherung/krankenversicherung-leistungen-tarife/Aerztliche-Leistungen-in-der-Krankenversicherung/Tarifsystem-Tarmed.html)
    
servers:
  - url: https://{environment}.tarmed-validator.ch/api/{version}
    variables:
      environment:
        default: api
        enum:
          - api
          - api.staging
      version:
        default: v1
        enum:
          - v1
security:
  - ApiKeyAuth: []

tags:
  - name: browser
    description: Read TARMED data (TARMED Browser API)
    externalDocs:
      url: http://www.tarmed-browser.ch
  - name: validator
    description: Validate TARMED data (TARMED Validator API)

paths:
  /validate:
    put:
      summary: Validate Single TARMED Invoice
      description: |
        Validate multiple TARMED services in a single requests. Useful for validating single invoices.
      tags:
        - validator
      parameters:
        - $ref: "#/components/parameters/locale"
        - $ref: "#/components/parameters/tarmedVersion"
      requestBody:
        description: Payload with configuration, patient, physician and services.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "#/components/schemas/Config"
                patient:
                  $ref: "#/components/schemas/Patient"
                physician:
                  $ref: "#/components/schemas/Physician"
                services:
                  type: array
                  items:
                    $ref: "#/components/schemas/Service"
      responses:
        "200":
          description: Validation status report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /validate-invoices:
    put:
      summary: Validate Multiple TARMED Invoices
      description: |
        Validate multiple invoices with multiple TARMED services in a single requests. Useful for validating multiple invoices (as presented to a patient). With this endpoint it is possible to validate all rules with the full patient history.
      tags:
        - validator
      parameters:
        - $ref: "#/components/parameters/locale"
        - $ref: "#/components/parameters/tarmedVersion"
      requestBody:
        description: Payload with configuration, patient, physician and invoices with services.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "#/components/schemas/Config"
                patient:
                  $ref: "#/components/schemas/Patient"
                physician:
                  $ref: "#/components/schemas/Physician"
                invoices:
                  type: array
                  description: Array of invoices
                  items:
                    properties:
                      internal_id:
                        oneOf:
                          - type: string
                          - type: integer
                        format: integer
                        example: 12345                        
                      case_nr:
                        oneOf:
                          - type: string
                          - type: integer
                        format: string
                        example: "C-001"
                        description: Case reference of the invoice. Needed for validation of service rules per case.
                      services:
                        type: array
                        description: Array of services of a single invoice
                        items:
                          $ref: "#/components/schemas/Service"
      responses:
        "200":
          description: Validation status report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /browser/chapters:
    get:
      summary: List TARMED chapters
      description: List TARMED chapters. Maximum of 100 chapters are returned. Pagination (limit, offset) and includes (chapter interpretations, services) can be used.
      tags:
        - browser
      parameters:
        - name: filter[level]
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 10
            example: 1
          required: false
          description: >
            Show only chapters of specific hierarchical level. `00` is level 0, `00.01` level 1, etc.
        - name: filter[parent]
          in: query
          schema:
            type: string
            example: "00.01"
          required: false
          description: Filter chapters by a specific parent chapter
        - name: page[limit]
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
          required: false
          description: limit number of returned records (1-100)
        - name: page[offset]
          in: query
          schema:
            type: integer
            minimum: 0
            example: 10
          required: false
          description: offset of returned records      
        - name: include
          in: query
          required: false
          description: "include associations of chapters: chapter interpretations, services"
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
              - chapter_interpretations
              - services
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: Array of TARMED chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/TarmedChapter"
                    - properties:
                        chapter_interpretations:
                          type: array
                          items:
                            allOf:
                              - $ref: "#/components/schemas/TarmedChapterInterpretation"
                        services:
                          type: array
                          items:
                            allOf:
                              - $ref: "#/components/schemas/TarmedServiceValue"
              examples:
                chapters:
                  $ref: "#/components/examples/chapters"
                chaptersFilterLevelAndParent:
                  $ref: "#/components/examples/chaptersFilterLevelAndParent"


  /browser/chapters/{code}:
    get:
      summary: Get TARMED chapter
      description: Get TARMED chapter. Includes (chapter interpretations, services) can be used.
      tags:
        - browser
      parameters:
        - name: code
          in: path
          description: chapter code
          required: true
          schema:
            type: string
        - name: include
          in: query
          required: false
          description: "include associations of chapters: chapter interpretations, services"
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
              - chapter_interpretations
              - services
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: TARMED chapter
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/TarmedChapter"

  /browser/services:
    get:
      summary: List TARMED services
      description: List TARMED services. Maximum of 100 services is returned. Pagination (limit, offset) and includes (service text, service groups, service blocks, chapter, service type, section, law, anesthesia risk) can be used.
      tags:
        - browser
      parameters:
        - name: page[limit]
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
          required: false
          description: limit number of returned records (1-100)
        - name: page[offset]
          in: query
          schema:
            type: integer
            minimum: 0
            example: 10
          required: false
          description: offset of returned records
        - name: include
          in: query
          required: false
          description: include associations like service texts, service groups/blocks, chapters, and more
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
              - service_text
              - service_groups
              - service_blocks
              - chapter
              - service_type
              - section
              - law
              - anesthesia_risk
        - name: filter
          in: query
          required: false
          description: >
            Filter services by specific fields or associations.
            The following fields of services are supported:
            
              * chapter\_code
              * experience\_code
              * law\_code
              * section\_code
              * service\_type\_code
            
            The following association fields are supported:
            
              * service_groups.code
              * service_blocks.code
          style: deepObject
          schema:
            type: object
            properties:
              chapter_code:
                type: string
                example: "02.01"
              experience_code:
                type: string
                example: "FMH05"
              law_code:
                type: string
                example: "01"
              section_code:
                type: string
                example: "0001"
              service_type_code:
                type: string
                example: "Z"
              service_groups.code:
                type: string
                example: "30"
              service_blocks.code:
                type: string
                example: "51"
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: Array of TARMED services
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/TarmedServiceValue"
                    - properties:
                        service_text:
                          $ref: "#/components/schemas/TarmedServiceText"
                        service_groups:
                          type: array
                          items:
                            allOf:
                              - $ref: "#/components/schemas/TarmedServiceGroup"
              examples:
                services:
                  $ref: "#/components/examples/services"
                serviceWithServiceText:
                  $ref: "#/components/examples/servicesWithServiceTextAndServiceGroups"

  /browser/services/{code}:
    get:
      summary: Get TARMED service
      description: Get TARMED service. Includes (service text, service groups, service blocks, chapter, service type, section, law, anesthesia risk) can be used.
      tags:
        - browser
      parameters:
        - name: code
          in: path
          description: TARMED service code
          required: true
          schema:
            type: string
            pattern: '^\d{2}\.\d{4}$'
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: TARMED service
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/TarmedServiceValue"
                  - properties:
                      service_text:
                        $ref: "#/components/schemas/TarmedServiceText"
                      service_groups:
                        type: array
                        items:
                          allOf:
                            - $ref: "#/components/schemas/TarmedServiceGroup"
              examples:
                service:
                  $ref: "#/components/examples/service"
                serviceWithServiceText:
                  $ref: "#/components/examples/serviceWithServiceText"  
                serviceWithServiceTextAndServiceGroups:
                  $ref: "#/components/examples/serviceWithServiceTextAndServiceGroups"
  /browser/service-blocks:
    get:
      summary: List TARMED service blocks
      description: List all TARMED service blocks.
      tags:
        - browser
      parameters:
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: Array of TARMED service blocks.

  /browser/service-blocks/{code}:
    get:
      summary: Get TARMED service block
      description: Get TARMED service block.
      tags:
        - browser
      parameters:
        - name: code
          in: path
          description: service block code
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: TARMED service block

  /browser/service-groups:
    get:
      summary: List TARMED service groups
      description: List all TARMED service groups.
      tags:
        - browser
      parameters:
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: Array of TARMED service groups

  /browser/service-groups/{code}:
    get:
      summary: Get TARMED service group
      description: Get TARMED service group.
      tags:
        - browser
      parameters:
        - name: code
          in: path
          description: service group code
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
        "200":
          description: TARMED service group

  /services/values/{code}:
    get:
      deprecated: true
      summary: Get values of a TARMED service
      tags:
        - browser
      description: "Get values of a TARMED service by nr. deprecated: will be removed with version v2"
      parameters:
        - name: code
          in: path
          description: TARMED Leistungsnummer
          required: true
          schema:
            type: string
            pattern: '^\d{2}\.\d{4}$'
          example: 00.0010
        - $ref: "#/components/parameters/tarmedVersion"
      responses:
       "200":
          description: A JSON array of one TARMED service
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TarmedServiceValue"
  /services/texts/{code}:
    get:
      deprecated: true
      summary: Get texts of a TARMED service
      tags:
        - browser
      description: "Get texts like name, medical and technical interpretation of a TARMED service by code. deprecated: will be removed with version v2"
      parameters:
        - name: code
          in: path
          description: TARMED Leistungsnummer
          required: true
          schema:
            type: string
            pattern: '^\d{2}\.\d{4}$'
          example: 00.0010
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
       "200":
          description: A JSON array of one TARMED service
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TarmedServiceText"
  /services/texts:
    get:
      deprecated: true
      summary: Get texts of TARMED services by query
      tags:
        - browser
      description: "Find TARMED services by code or title. Returns an array of TARMED text objects with name, medical and technical interpretation. Max. 30 items returned. deprecated: will be removed with version v2"
      parameters:
        - name: q
          in: query
          description: String to search for.
          schema:
            type: string
            example: leistung
        - $ref: "#/components/parameters/tarmedVersion"
        - $ref: "#/components/parameters/locale"
      responses:
       "200":
          description: A JSON array of one TARMED service
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TarmedServiceText"        
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Config:
      type: object
      properties:
        ignore_errors:
          type: array
          items:
            type: number
            format: integer
            example:
            - 5007
            - 6000
            description: error and warning codes to ignore (will be placed in ignored array response)
        conditions:
          type: object
          description: Set special conditions as option for validation.
          properties:
            inaccurate_quantity_rules:
              type: string
              nullable: true
              enum:
                - warning
                - error
                - null
              description: >
                Validate inaccurate quantity rules (pro Aufenthalt, pro Testreihe, pro Schwangerschaft, pro Geburt, pro Eingriff, etc.) which can't be validated by the given data:
                  * `warning` - return validation result as warning
                  * `error` - return validation result as error
                  * `null` - (default) option is not set, quantity rules are ignored.
            ignore_cumulations:
              type: boolean
              description: >
                Ignores all cumulation erros/warnings and returns possible errors/warnings in the `ignored` object. Useful to focus validation of TARMED invoices to quantity, patient and reference rules:
                  * `true` - cumulation errors/warnings are returned in the `ignored` object
                  * `false` - (default) cumulation errors/warnings are not ignored for validation
            force_cumulation_validity:
              description: >
                Forces all services of the given types to be valid, even if these are defined to not to be included by cumulation exclusion. Quantity rules are still validated. Default: not set.
              type: object
              properties:
                chapters:
                  type: array
                  description: Services of the given chapters are always allowed to include.
                  items:
                    type: string
                  example:
                   - "00.01"
                   - "00.03"
                #groups:
                #  type: array
                #  description: Services of the given group are always allowed to include on an invoice.
                #  items:
                #    type: string
                #  example:
                #   - "25"
                #   - "30"
                #blocks:
                #  type: array
                #  description: Services of the given block are always allowed to include on an invoice.
                #  items:
                #    type: string
                #  example:
                #   - "03"
                #   - "16"
                #services:
                #  type: array
                #  description: Given services are always allowed to include on an invoice.
                #  items:
                #    type: string
                #  example:
                #   - "00.0010"
                #   - "00.0015"
                #   - "00.0020"
    Patient:
      type: object
      properties:
        dob:
          type: string
          format: date
        gender:
          type: string
          enum: [f, m]
          description: >
            Gender:
             * `f` - Female
             * `m` - Male
    Physician:
      type: object
      properties:
        qualifications:
          type: array
          items:
            properties:
              code:
                type: string
                format: string
                example: "0100"

    Service:
      type: object
      properties:
        code:
          type: string
          description: TARMED code
          example: 00.0010
        ref_code:
          type: string
          description: TARMED reference code
          example: 00.0010
        quantity:
          type: number
          format: integer
        session:
          type: number
          format: integer
        side:
          type: string
          enum: [l, r]
          description: >
            Gender:
             * `l` - left
             * `r` - right
        date:
          type: string
          format: date
        internal_id:
          oneOf:
            - type: string
            - type: integer
          format: integer
          example: 12345
    Report:
      type: object
      properties:
        validation:
          type: string
          enum: [valid, invalid]
          description: >
            validation status
             * `valid` - validation succeeded
             * `invalid` - validation failed, detailled information in errors array
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorCode"
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ErrorCode"
        ignored:
          type: object
          description: ignored errors and warnings when configuration option `ignore_errors` is set
          properties:
            errors:
              type: array
              items:
                $ref: "#/components/schemas/ErrorCode"
            warnings:
              type: array
              items:
                $ref: "#/components/schemas/ErrorCode"
    ErrorCode:
      type: object
      properties:
        code:
          type: integer
          description: >
            error code:
             * `2000` - TARMED version not found
             * `2001` - TARMED code not found
             * `2010` - Cumulation invalid: exclusion
             * `2020` - Cumulation invalid: limited inclusion
             * `2051` - Missing reference (addition)
             * `2052` - Referenced parent not listed
             * `2053` - Referenced parent not allowed
             * `2057` - Reference error: service type reference (R)
             * `2070` - Side error: side of service not defined
             * `2071` - Side error: invalid side given
             * `3001` - Patient error: invalid gender
             * `3002` - Patient error: invalid date of birth
             * `3010` - Patient error: service not allowed for gender
             * `3011` - Patient error: service not allowed for patient's age
             * `4002` - Service attribute error: invalid date
             * `5007` - Quantity error: quantity per session invalid
             * `5008` - Quantity error: quantity per case invalid
             * `5009` - Quantity error: quantity per patient invalid
             * `5010` - Quantity error: quantity per side invalid
             * `5011` - Quantity error: quantity per inhabitation (Aufenthalt) invalid (i)
             * `5012` - Quantity error: quantity per test serie (Testreihe) invalid (i)
             * `5013` - Quantity error: quantity per pregnancy (Schwangerschaft) invalid (i)
             * `5014` - Quantity error: quantity per birth (Geburt) invalid (i)
             * `5015` - Quantity error: quantity per radiation phase (Bestrahlungsphase) invalid (i)
             * `5016` - Quantity error: quantity per transmittal (Einsendung) invalid (i)
             * `5017` - Quantity error: quantity per autopsy (Autopsie) invalid (i)
             * `5018` - Quantity error: quantity per expertise (Gutachten) invalid (i)
             * `5019` - Quantity error: quantity per intervention (Eingriff) invalid (i)
             * `5021` - Quantity error: quantity per day invalid
             * `5022` - Quantity error: quantity per week invalid
             * `5023` - Quantity error: quantity per month invalid
             * `5026` - Quantity error: quantity per year invalid
             * `5031` - Quantity error: quantity per radiation phase and volume (Bestrahlungsphase und Bestrahlungsvolumen) invalid (i)
             * `5040` - Quantity error: quantity per joint region (Gelenkregion) invalid (i)
             * `5043` - Quantity error: quantity per examination (Untersuchung) invalid (i)
             * `5108` - Quantity warning: case not set for service with matching rule
             * `5222` - Quantity error: quantity of service group per week invalid
             * `5223` - Quantity error: quantity of service group per month invalid
             * `6000` - Qualification error: service not allowed due to missing qualification
             * `6004` - Qualification error: qualification not found
             * `6005` - Qualification error: malformed physician, qualification format
             * `6100` - Qualification warning: qualification not set.
             * `6101` - Qualification warning: qualification not set. Service has special cumulation exceptions.
             * `7000` - Warning: Duplicate entry in session found
             
             (i): inaccurrate validation, see config.conditions for details
        message:
          type: string
          description: Additional detail about the validation error
        index:
          type: number
          format: integer
          description: When an array was given, index points to the validated element
        internal_id:
          oneOf:
            - type: string
            - type: integer
          format: integer
          example: 12345
          description: ID of given position in request which the error or warning refers to.

    TarmedServiceValue:
      allOf:
      - type: object
        properties:
          code:
            type: string
            description: TARMED Leistungsnummer (LEISTUNG.LNR)
          assi_count:
            type: number
            format: integer
            description: Anzahl Assistenten (LEISTUNG.ANZ_ASSI)
          change_min:
            type: number
            format: integer
            description: Wechselzeit (LEISTUNG.WECHSEL_MIN)
          dignity_quant:
            type: string
            description: "DignitÃ¤ts-Nr.: \"FMH\" und Nr. zweistellig (LEISTUNG.QT_DIGNITAET)"
          indication_min:
            type: number
            format: integer
            description: Befund (LEISTUNG.BEFUND_MIN)
          prepost_min:
            type: number
            format: integer
            description: Vorbereitung/Nachbereitung (LEISTUNG.VBNB_MIN)
          rate_factor_assi:
            type: number
            format: float
            description: Taxpunkte Assistent (LEISTUNG.TP_ASSI)
          rate_factor_doc:
            type: number
            format: float
            description: Taxpunkte Arztleistung (LEISTUNG.TP_AL)
          rate_factor_pdoc:
            type: number
            format: float
            description: "Taxpunkte Arztleistung ohne FMH (calculated: LEISTUNG.TP_AL * LEISTUNG.F_AL_R)"
          rate_factor_tech:
            type: number
            format: float
            description: Taxpunkte Technische Leistung (LEISTUNG.TP_TL)
          room_min:
            type: number
            format: integer
            description: Raumzeit (LEISTUNG.RAUM_MIN, not from Einstein ;) )
          service_min:
            type: number
            format: integer
            description: Leistung im engeren Sinne (LEISTUNG.LSTGIMES_MIN)
          sex:
            type: string
            enum: [male, female]
            description: >
              Patientengeschlecht (LEISTUNG.SEX)
               * `male` - MÃ¤nnlich
               * `female` - Weiblich
          side:
            type: boolean
            description: >
              Seitenangabe (LEISTUNG.SEITE)
               * `true` - Die Angabe auf welcher Seite die Leistung erbracht wurde ist zwingend
               * `false` - keine Seitenangabe nÃ¶tig
          surcharge_doc:
            type: number
            format: float
            description: Zuschlags- oder Reduktions-Faktor auf Arztleistung (LEISTUNG.F_AL)
          surcharge_pdoc:
            type: number
            format: float
            description: Zuschlags- oder Reduktions-Faktor auf Arztleistung ohne FMH (LEISTUNG.F_AL_R)
          surcharge_tech:
            type: number
            format: float
            description: Zuschlags- oder Reduktions-Faktor auf techn. Leistung (LEISTUNG.F_TL)
        example:
          $ref: "#/components/examples/service/value"
      - $ref: "#/components/schemas/TarmedDates"

    TarmedServiceText:
      allOf:
        - type: object
          properties:
            code:
              type: string
              description: TARMED nr (LEISTUNG_TEXT.LNR)
            title:
              type: string
              description: Title of the service (LEISTUNG_TEXT.BEZ_255)
            medical_information:
              type: string
              description: Medical interpretation (LEISTUNG_TEXT.MED_INTERPRET)
            technical_information:
              type: string
              description: Technical interpretation (LEISTUNG_TEXT.TECH_INTERPRET)
            locale:
              $ref: "#/components/schemas/TarmedLocaleEnum"
          example:
            code: "00.0010"
            title: "Konsultation, erste 5 Min. (Grundkonsultation)"
            medical_information: "Beinhaltet alle Ã¤rztlichen Leistungen, die der Facharzt in seiner..."
            technical_information: "Technische Interpretation ..."
            locale: "D"
        - $ref: "#/components/schemas/TarmedDates"

    TarmedServiceGroup:
      allOf:
        - type: object
          properties:
            code:
              type: string
              description: Code of service group (CT_LEISTUNG_GRUPPEN.CODE)
            title:
              type: string
              description: Title of service group (CT_LEISTUNG_GRUPPEN.GRUPPE)
            locale:
              $ref: "#/components/schemas/TarmedLocaleEnum"
            show:
              type: boolean
              description: Show in browser (CT_LEISTUNG_GRUPPEN.ZEIGEN)
            text:
              type: string
              description: Interpretation (CT_LEISTUNG_GRUPPEN.INTERPRETATION)
        - $ref: "#/components/schemas/TarmedDates"

    TarmedChapter:
      allOf:
        - type: object
          properties:
            code:
              type: string
              description: Code of chapter (KAPITEL_TEXT.KNR)
            title:
              type: string
              description: Title of chapter (KAPITEL.BEZ_255)
            locale:
              $ref: "#/components/schemas/TarmedLocaleEnum"
          example:
            $ref: "#/components/examples/chapter/value"
        - $ref: "#/components/schemas/TarmedDates"

    TarmedChapterInterpretation:
      allOf:
        - type: object
          properties:
            chapter_code:
              type: string
              description: Foreign key to chapter code (KAPITEL_INTERPRETATION_TEXT.KNR)
            nr:
              type: integer
              description: Number of the chapter interpretation (KAPITEL_INTERPRETATION_TEXT.KAP_INTERPRET_NR)
            title:
              type: string
              description: Title of the chapter interpretation (KAPITEL_INTERPRETATION_TEXT.KAP_INTERPRET_TITEL)
            interpretation:
              type: string
              description: Text of the chapter interpretation (KAPITEL_INTERPRETATION_TEXT.KAP_INTERPRET_TEXT)
            locale:
              $ref: "#/components/schemas/TarmedLocaleEnum"
          example:
            $ref: "#/components/examples/chapterInterpretation/value"
        - $ref: "#/components/schemas/TarmedDates"        

    TarmedDates:
      type: object
      properties:
        valid_from:
          type: string
          format: date
          description: gÃ¼ltig von (*.GUELTIG_VON)
        valid_until:
          type: string
          format: date
          description: gÃ¼ltig bis (*.GUELTIG_BIS)
        change_date:
          type: string
          format: date
          description: mutiert am (*.MUT_DAT)
      example:
        valid_from: "2018-01-01"
        valid_until: "2999-12-31"
        change_date: "2017-03-12"

    TarmedLocaleEnum:
      type: string
      enum: [D, F, I]
      description: >
        Locale:
        
         * `D` - German
         * `F` - French
         * `I` - Italian      

  parameters:
    locale:
      name: locale
      in: query
      description: >
        Returns the validation errors or the TARMED data in the given language:
        
         * `de`: german (defaut)
         * `fr`: french
         * `it`: italian
      schema:
        type: string
        example: de
    tarmedVersion:
      name: tarmed_version
      in: query
      description: >
        Selects the TARMED tarif version:
        
         * `01.09` (default)
         * `01.08.01_BR`
         * List of all versions: [https://www.tarmed-browser.ch/de/versionen](https://www.tarmed-browser.ch/de/versionen)
      schema:
        type: string
        example: 01.09
    invoiceId:
      name: invoiceId
      in: path
      description: ID of the invoice
      required: true
      schema:
        type: string

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string

  examples:
    chapter:
      value:
        code: "02.01"
        title: "Psychiatrische Diagnostik und Therapie"
        locale: "D"
      summary: TARMED chapter 02.01

    chapters:
      summary: 5 Chapters
      value:
        - code: '00'
          locale: D
          title: Grundleistungen
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        - code: '00.01'
          locale: D
          title: Allgemeine Grundleistungen
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        - code: '00.01.01'
          locale: D
          title: Konsultation, Besuch, WegentschÃ¤digung u.a.
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        - code: '00.02'
          locale: D
          title: Leistungspakete
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        - code: '00.02.01'
          locale: D
          title: Untersuchungen
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'

    chaptersFilterLevelAndParent:
      summary: "Chapters filtered: level 3, parent 05.01.02"
      value:
        - code: 05.01.02.01
          locale: D
          title: Elektroneurogramm ({ENG}), Elektromyogramm ({EMG})
          valid_from: '2006-04-01'
          valid_until: '2999-12-31'
          change_date: '2006-01-13'
        - code: 05.01.02.02
          locale: D
          title: Elektroenzephalogramm ({EEG})
          valid_from: '2006-04-01'
          valid_until: '2999-12-31'
          change_date: '2006-01-13'
        - code: 05.01.02.03
          locale: D
          title: Evozierte Potentiale, Monitoring
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'


    chapterInterpretation:
      value:
        chapter_code: "02"
        nr: 1
        title: "Luminotherapie"
        interpretation: "Lichtbehandlung zuhause:\n\n- Arztleistungen (Instruktion, Beratung) mit Leistungen (02.0010) und (02.0020), allenfalls mit 'Allgemeine Grundleistungen' (durch Nichtpsychiater) verrechenbar\n\n- Materialkosten gemÃ¤ss {20}."
        locale: "D"
      summary: First Chapter Interprtation of Chapter 02
      
    service:
      value:
        code: "00.0010"
        assi_count: 0
        change_min: 0
        dignity_quant: "FMH05"
        indication_min: 0
        prepost_min: 0
        rate_factor_assi: 0
        rate_factor_doc: 10.42
        rate_factor_pdoc: 9.69
        rate_factor_tech: 8.19
        room_min: 5
        service_min: 5
        sex: null
        side: false
        surcharge_doc: 1
        surcharge_pdoc: 0.93
        surcharge_tech: 1
      summary: Service 00.0010
    serviceText:
      value:
        code: "00.0010"
        title: "Konsultation, erste 5 Min. (Grundkonsultation)"
        medical_information: "Beinhaltet alle Ã¤rztlichen Leistungen, die der Facharzt in seiner..."
        technical_information: "Technische Interpretation ..."
        locale: "D"
        valid_from: "2018-01-01"
        valid_until: "2999-12-31"
        change_date: "2017-09-01"
      summary: Service Text 00.0010

    serviceWithServiceText:
      value:
        code: "00.0010"
        assi_count: 0
        change_min: 0
        dignity_quant: "FMH05"
        indication_min: 0
        prepost_min: 0
        rate_factor_assi: 0
        rate_factor_doc: 10.42
        rate_factor_pdoc: 9.69
        rate_factor_tech: 8.19
        room_min: 5
        service_min: 5
        sex: null
        side: false
        surcharge_doc: 1
        surcharge_pdoc: 0.93
        surcharge_tech: 1
        service_text:
          code: "00.0010"
          title: "Konsultation, erste 5 Min. (Grundkonsultation)"
          medical_information: "Beinhaltet alle Ã¤rztlichen Leistungen, die der Facharzt in seiner..."
          technical_information: "Technische Interpretation ..."
          locale: "D"
          valid_from: "2018-01-01"
          valid_until: "2999-12-31"
          change_date: "2017-09-01"
      summary: Service 00.0010 including service_text

    serviceWithServiceTextAndServiceGroups:
      summary: Service 00.0010 including service_text,service_groups
      value:
        code: '00.0010'
        additional_min: 0
        anesthesia_risk_code: 
        assistance_quantity: 0
        change_min: 0
        chapter_code: 00.01.01
        experience_code: FMH05
        indication_min: 0
        law_code: '01'
        prepost_min: 0
        rate_factor_assistance: 0
        rate_factor_doctor: 10.42
        rate_factor_technical: 8.19
        room_min: 5
        section_code: '0001'
        service_type_code: H
        sex: 
        side: false
        surcharge_factor_doctor: 1
        surcharge_factor_doctor_pract: 0.93
        surcharge_factor_technical: 1
        treatment_min: 5
        visit_content: N
        valid_from: '2018-01-01'
        valid_until: '2999-12-31'
        change_date: '2017-03-12'
        service_text:
          code: '00.0010'
          title: Konsultation, erste 5 Min. (Grundkonsultation)
          locale: D
          medical_interpretation: |-
            Beinhaltet alle Ã¤rztlichen Leistungen, die der Facharzt in seiner Praxis oder der Arzt bei ambulanten Patienten im Spital ohne oder mit einfachen Hilfsmitteln (etwa Inhalt 'Besuchskoffer') am Patienten hinsichtlich der Beschwerden und Erscheinungen erbringt, derentwegen dieser zum Facharzt kommt, bzw. gebracht wird und hinsichtlich der Beschwerden und Erscheinungen, die wÃ¤hrend der gleichen Behandlungsdauer auftreten.
        
            Beinhaltet BegrÃ¼ssung, Verabschiedung, nicht besonders tarifierte Besprechungen und Untersuchungen, nicht besonders tarifierte Verrichtungen (z.B.: bestimmte Injektionen, VerbÃ¤nde usw.), Begleitung zu und Ãbergabe (inkl. Anordnungen) an Hilfspersonal betreffend Administration, technische und kurative Leistungen, Medikamentenabgabe (in Notfallsituation u/o als Starterabgabe), auf Konsultation bezogene unmittelbar vorgÃ¤ngige/anschliessende Akteneinsicht/AkteneintrÃ¤ge.
          technical_interpretation: 
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        service_groups:
        - code: '03'
          title: Tarifpositionen bei denen der Zuschlag fÃ¼r hausÃ¤rztliche Leistungen in der
            Arztpraxis (00.0015) abgerechnet werden kann.
          locale: D
          show: true
          text: ''
          valid_from: '2018-01-01'
          valid_until: '2999-12-31'
          change_date: '2017-09-01'
        - code: '18'
          title: Allgemeine Grundleistungen
          locale: D
          show: true
          text: ''
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'
        - code: '58'
          title: Allgemeine Grundleistungen nicht kumulierbar mit Konsilium
          locale: D
          show: true
          text: ''
          valid_from: '2001-01-01'
          valid_until: '2999-12-31'
          change_date: '2001-11-08'

    services:
      summary: 2 Services
      value:
        - code: '00.0010'
          additional_min: 0
          anesthesia_risk_code: 
          assistance_quantity: 0
          change_min: 0
          chapter_code: 00.01.01
          experience_code: FMH05
          indication_min: 0
          law_code: '01'
          prepost_min: 0
          rate_factor_assistance: 0
          rate_factor_doctor: 10.42
          rate_factor_technical: 8.19
          room_min: 5
          section_code: '0001'
          service_type_code: H
          sex: 
          side: false
          surcharge_factor_doctor: 1
          surcharge_factor_doctor_pract: 0.93
          surcharge_factor_technical: 1
          treatment_min: 5
          visit_content: N
          valid_from: '2018-01-01'
          valid_until: '2999-12-31'
          change_date: '2017-03-12'
        - code: '00.0015'
          additional_min: 
          anesthesia_risk_code: 
          assistance_quantity: 0
          change_min: 0
          chapter_code: 00.01.01
          experience_code: FMH05
          indication_min: 0
          law_code: '01'
          prepost_min: 0
          rate_factor_assistance: 0
          rate_factor_doctor: 10.88
          rate_factor_technical: 0
          room_min: 0
          section_code: '0001'
          service_type_code: Z
          sex: 
          side: false
          surcharge_factor_doctor: 1
          surcharge_factor_doctor_pract: 0.93
          surcharge_factor_technical: 1
          treatment_min: 0
          visit_content: N
          valid_from: '2018-01-01'
          valid_until: '2999-12-31'
          change_date: '2017-03-12'


    servicesWithServiceTextAndServiceGroups:
      summary: 2 Services includes service_text,service_groups
      value:
        - code: '00.0010'
          additional_min: 0
          anesthesia_risk_code: 
          assistance_quantity: 0
          change_min: 0
          chapter_code: 00.01.01
          experience_code: FMH05
          indication_min: 0
          law_code: '01'
          prepost_min: 0
          rate_factor_assistance: 0
          rate_factor_doctor: 10.42
          rate_factor_technical: 8.19
          room_min: 5
          section_code: '0001'
          service_type_code: H
          sex: 
          side: false
          surcharge_factor_doctor: 1
          surcharge_factor_doctor_pract: 0.93
          surcharge_factor_technical: 1
          treatment_min: 5
          visit_content: N
          valid_from: '2018-01-01'
          valid_until: '2999-12-31'
          change_date: '2017-03-12'
          service_text:
            code: '00.0010'
            title: Konsultation, erste 5 Min. (Grundkonsultation)
            locale: D
            medical_interpretation: |-
              Beinhaltet alle Ã¤rztlichen Leistungen, die der Facharzt in seiner Praxis oder der Arzt bei ambulanten Patienten im Spital ohne oder mit einfachen Hilfsmitteln (etwa Inhalt 'Besuchskoffer') am Patienten hinsichtlich der Beschwerden und Erscheinungen erbringt, derentwegen dieser zum Facharzt kommt, bzw. gebracht wird und hinsichtlich der Beschwerden und Erscheinungen, die wÃ¤hrend der gleichen Behandlungsdauer auftreten.
        
              Beinhaltet BegrÃ¼ssung, Verabschiedung, nicht besonders tarifierte Besprechungen und Untersuchungen, nicht besonders tarifierte Verrichtungen (z.B.: bestimmte Injektionen, VerbÃ¤nde usw.), Begleitung zu und Ãbergabe (inkl. Anordnungen) an Hilfspersonal betreffend Administration, technische und kurative Leistungen, Medikamentenabgabe (in Notfallsituation u/o als Starterabgabe), auf Konsultation bezogene unmittelbar vorgÃ¤ngige/anschliessende Akteneinsicht/AkteneintrÃ¤ge.
            technical_interpretation: 
            valid_from: '2001-01-01'
            valid_until: '2999-12-31'
            change_date: '2001-11-08'
          service_groups:
          - code: '03'
            title: Tarifpositionen bei denen der Zuschlag fÃ¼r hausÃ¤rztliche Leistungen in
              der Arztpraxis (00.0015) abgerechnet werden kann.
            locale: D
            show: true
            text: ''
            valid_from: '2018-01-01'
            valid_until: '2999-12-31'
            change_date: '2017-09-01'
          - code: '18'
            title: Allgemeine Grundleistungen
            locale: D
            show: true
            text: ''
            valid_from: '2001-01-01'
            valid_until: '2999-12-31'
            change_date: '2001-11-08'
          - code: '58'
            title: Allgemeine Grundleistungen nicht kumulierbar mit Konsilium
            locale: D
            show: true
            text: ''
            valid_from: '2001-01-01'
            valid_until: '2999-12-31'
            change_date: '2001-11-08'
        - code: '00.0015'
          additional_min: 
          anesthesia_risk_code: 
          assistance_quantity: 0
          change_min: 0
          chapter_code: 00.01.01
          experience_code: FMH05
          indication_min: 0
          law_code: '01'
          prepost_min: 0
          rate_factor_assistance: 0
          rate_factor_doctor: 10.88
          rate_factor_technical: 0
          room_min: 0
          section_code: '0001'
          service_type_code: Z
          sex: 
          side: false
          surcharge_factor_doctor: 1
          surcharge_factor_doctor_pract: 0.93
          surcharge_factor_technical: 1
          treatment_min: 0
          visit_content: N
          valid_from: '2018-01-01'
          valid_until: '2999-12-31'
          change_date: '2017-03-12'
          service_text:
            code: '00.0015'
            title: "+ Zuschlag fÃ¼r hausÃ¤rztliche Leistungen in der Arztpraxis"
            locale: D
            medical_interpretation: |-
              Darf nur im Zusammenhang mit der Erbringung von hausÃ¤rztlichen Leistungen abgerechnet werden und wenn dem Patienten am selben Tag keine spezialÃ¤rztlichen Leistungen durch den gleichen Leistungserbringer verrechnet werden.
        
              Darf nicht von ambulanten Diensten von SpitÃ¤lern abgerechnet werden.
            technical_interpretation: 
            valid_from: '2014-10-01'
            valid_until: '2999-12-31'
            change_date: '2014-07-01'
          service_groups:
          - code: '03'
            title: Tarifpositionen bei denen der Zuschlag fÃ¼r hausÃ¤rztliche Leistungen in
              der Arztpraxis (00.0015) abgerechnet werden kann.
            locale: D
            show: true
            text: ''
            valid_from: '2018-01-01'
            valid_until: '2999-12-31'
            change_date: '2017-09-01'


    serviceGroup:
      value:
        code: "03"
        locale: "D"
        show: true
        text: ""
        title: "Tarifpositionen bei denen der Zuschlag fÃ¼r hausÃ¤rztliche Leistungen in der Arztpraxis (00.0015) abgerechnet werden kann."
        valid_from: "2018-01-01"
        valid_until: "2999-12-31"
        change_date: "2017-09-01"
      summary: TARMED Service Group 03
